name: scatlasvae
channels:
  - conda-forge
  - bioconda
  - pytorch
dependencies:
  - conda-forge::python=3.8
  - conda-forge::setuptools=59.5.0
  - conda-forge::pip
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu117
      - --extra-index-url https://pypi.nvidia.com
      - sphinx_rtd_theme==1.2.0
      - sphinx-hoverxref==1.3.0
      - tabulate==0.9.0
      - anndata==0.8.0
      - scanpy==1.8.1
      - scirpy==0.10.1
      - pandas==1.4.2
      - matplotlib==3.5.2
      - umap-learn==0.5.1
      - seaborn==0.11.2
      - scikit-learn==0.24.1 
      - einops==0.4.1 
      - biopython==1.79
      - plotly==5.10.0
      - numba==0.57.1
      - numpy==1.21.6
